// BAKED-IN exact Bayer-Diaconis total variation anchors.
//
// These constants are the output of tools/exact_tv.py (exact big-rational
// arithmetic over Eulerian numbers — deliberately NOT implemented in TS; the
// intermediate integers are ~10^150). The validation gate compares GSR
// simulation behaviour against these values, and a test cross-checks the
// 52-card row against the published Bayer-Diaconis table.
//
// To regenerate: python3 tools/exact_tv.py  and paste the output below.

// Generated by tools/exact_tv.py on 2026-08-04 (script v1).
// Exact Bayer-Diaconis TV distance to uniform after m GSR riffles,
// rounded to 6 decimal places. Do not edit by hand; rerun the script.
export const EXACT_TV_52: readonly number[] = [1.000000, 1.000000, 1.000000, 1.000000, 0.923733, 0.613550, 0.334061, 0.167159, 0.085420, 0.042946, 0.021502, 0.010755]; // m=1..12
export const EXACT_TV_100: readonly number[] = [1.000000, 1.000000, 1.000000, 1.000000, 1.000000, 0.981526, 0.747347, 0.428803, 0.223922, 0.112168, 0.056637, 0.028388, 0.014203, 0.007103, 0.003551, 0.001776]; // m=1..16

/** TV(m) for deck size n (m is 1-based; returns 0 beyond the table). */
export function exactTV(n: 52 | 100, m: number): number {
  const table = n === 52 ? EXACT_TV_52 : EXACT_TV_100;
  if (m < 1) return 1;
  return table[m - 1] ?? 0;
}
