#!/usr/bin/env python3
"""Exact Bayer-Diaconis total variation distance to uniform after m GSR riffles.

ONE-TIME provenance script. Its output is pasted into src/sim/anchors.ts;
it is never run by the app or the CI build.

Formula (Bayer & Diaconis 1992, "Trailing the Dovetail Shuffle to its Lair"):
after m GSR riffles of an n-card deck, the probability of any permutation with
exactly r rising sequences is

    P_m(pi) = 2^(-mn) * C(2^m + n - r, n)

so, with A(n, r) = number of permutations of n with exactly r rising sequences
(the Eulerian number <n, r-1>, i.e. permutations with r-1 descents),

    TV(m) = (1/2) * sum_{r=1..n} A(n, r) * | 2^(-mn) * C(2^m + n - r, n) - 1/n! |

Everything is exact: Python big ints and fractions.Fraction. The magnitudes
involved (~10^150) are why this is not implemented in TypeScript.

Convention check: the published 52-card table (Bayer-Diaconis Table 1) is
TV ~= 1.000, 1.000, 1.000, 1.000, 0.924, 0.614, 0.334, 0.167 for m=1..8.
This script asserts those values before printing anything.

Usage: python3 tools/exact_tv.py   (takes a few seconds)
"""

from fractions import Fraction
from math import comb, factorial
import datetime


def eulerian_rising(n: int) -> list[int]:
    """A[r] for r=1..n: permutations of n with exactly r rising sequences.

    A permutation has r rising sequences iff its inverse has r-1 descents, so
    these are the classical Eulerian numbers <n, k> with k = r - 1.
    Recurrence: <n, k> = (k+1)<n-1, k> + (n-k)<n-1, k-1>.
    """
    row = [1]  # n=1: one permutation, one rising sequence (k=0)
    for m in range(2, n + 1):
        prev = row
        row = [0] * m
        for k in range(m):
            a = (k + 1) * prev[k] if k < len(prev) else 0
            b = (m - k) * prev[k - 1] if k >= 1 else 0
            row[k] = a + b
    return row  # row[k] = <n, k> = permutations with r = k+1 rising sequences


def exact_tv(n: int, m: int, eul: list[int]) -> Fraction:
    nfact = factorial(n)
    two_mn = 2 ** (m * n)
    uniform = Fraction(1, nfact)
    total = Fraction(0)
    for k in range(n):  # r = k + 1 rising sequences
        r = k + 1
        p = Fraction(comb(2**m + n - r, n), two_mn)
        total += eul[k] * abs(p - uniform)
    return total / 2


def main() -> None:
    # Cross-check convention against the published 52-card values first.
    eul52 = eulerian_rising(52)
    assert sum(eul52) == factorial(52)
    published = [1.000, 1.000, 1.000, 1.000, 0.924, 0.614, 0.334, 0.167]
    for m, want in enumerate(published, start=1):
        got = float(exact_tv(52, m, eul52))
        assert abs(got - want) < 5e-4, f"m={m}: got {got}, published {want}"

    today = datetime.date.today().isoformat()
    print(f"// Generated by tools/exact_tv.py on {today} (script v1).")
    print("// Exact Bayer-Diaconis TV distance to uniform after m GSR riffles,")
    print("// rounded to 6 decimal places. Do not edit by hand; rerun the script.")
    for n, mmax in ((52, 12), (100, 16)):
        eul = eulerian_rising(n)
        assert sum(eul) == factorial(n)
        vals = [float(exact_tv(n, m, eul)) for m in range(1, mmax + 1)]
        body = ", ".join(f"{v:.6f}" for v in vals)
        print(f"export const EXACT_TV_{n}: readonly number[] = [{body}]; // m=1..{mmax}")


if __name__ == "__main__":
    main()
